name: settheorytalks cronjob

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: toolchain
      - run: |
          echo Configure git
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo install deps
          npm i
          echo run build
          npm run build
          git add index.html
          git commit -m "generated"
          git push
