name: settheorytalks cronjob

on:
  schedule:
    - cron: '17 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          sudo apt-get install wget
          echo configure git
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo install deps
          npm i
          echo run build
          npm run build
          git add index.html
          git commit -m "chore: cron job" || true
          git push
